preset: psr2

enabled:
  - encoding
  - full_opening_tag
  - blank_line_after_namespace
  - class_definition
  - elseif
  - encoding
  - full_opening_tag
  - function_declaration
  - indentation
  - lowercase_constants
  - lowercase_keywords
  - method_argument_space_strict
  - method_visibility_required
  - no_break_comment
  - no_closing_tag
  - no_spaces_after_function_name
  - no_spaces_inside_parenthesis
  - no_trailing_whitespace
  - no_trailing_whitespace_in_comment
  - property_visibility_required
  - psr2_braces
  - single_blank_line_at_eof
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - switch_case_semicolon_to_colon
  - switch_case_space
  - unix_line_endings
