language: php

sudo: required

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

install:
  - ./travis-install.sh
  - travis_retry composer install --no-interaction

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

script:
  - phpunit --no-coverage
